### ISSUE TITLE
Fargate agent stuck "Waiting for agent to connect"

### ISSUE THREAD

**Issue by bwolin** [jenkinsci/amazon-ecs-plugin#102]
I'm working through setting this up, but I am unable to run the suggested sample pipeline from 

[cloudbees/jnlp-slave-with-java-build-tools
](https://github.com/cloudbees/jnlp-slave-with-java-build-tools-dockerfile)

```
node ("jenkins-ecs-worker") {
    git "https://github.com/cloudbees-community/game-of-life"
    withMaven(mavenSettingsConfig:'my-maven-settings') {
       sh "mvn clean deploy"
    }
}
```
The ECS Fargate worker appears to start fine but never connects:

```
2019-06-11 14:03:19.003+0000 [id=42]	INFO	c.c.j.plugins.amazonecs.ECSCloud#provision: Asked to provision 1 agent(s) for: jenkins-ecs-worker
2019-06-11 14:03:19.003+0000 [id=42]	INFO	c.c.j.plugins.amazonecs.ECSCloud#provision: In provisioning : []
2019-06-11 14:03:19.003+0000 [id=42]	INFO	c.c.j.plugins.amazonecs.ECSCloud#provision: Excess workload after pending ECS agents: 1
2019-06-11 14:03:19.003+0000 [id=42]	INFO	c.c.j.plugins.amazonecs.ECSCloud#provision: Will provision ECS Agent jenkins-ecs-worker, for label: jenkins-ecs-worker
2019-06-11 14:03:19.003+0000 [id=42]	INFO	h.s.NodeProvisioner$StandardStrategyImpl#apply: Started provisioning ECS Agent jenkins-ecs-worker from jenkins-build-cluster with 1 executors. Remaining excess workload: 0
2019-06-11 14:03:29.020+0000 [id=40]	INFO	hudson.slaves.NodeProvisioner$2#run: ECS Agent jenkins-ecs-worker provisioning successfully completed. We have now 2 computer(s)
2019-06-11 14:03:29.191+0000 [id=32033]	INFO	c.c.j.p.amazonecs.ECSService#registerTemplate: Match on container definition: true
2019-06-11 14:03:29.191+0000 [id=32033]	INFO	c.c.j.p.amazonecs.ECSService#registerTemplate: Match on volumes: true
2019-06-11 14:03:29.191+0000 [id=32033]	INFO	c.c.j.p.amazonecs.ECSService#registerTemplate: Match on task role: true
2019-06-11 14:03:29.191+0000 [id=32033]	INFO	c.c.j.p.amazonecs.ECSService#registerTemplate: Match on execution role: true
2019-06-11 14:03:29.191+0000 [id=32033]	INFO	c.c.j.p.amazonecs.ECSService#registerTemplate: Match on network mode: true
2019-06-11 14:03:29.191+0000 [id=32033]	INFO	c.c.j.p.amazonecs.ECSLauncher#runECSTask: [jenkins-build-cluster-pbxr1]: Starting agent with task definition arn:aws:ecs:us-east-1:435433059373:task-definition/jenkins-build-cluster-jenkins-ecs-worker:4}
2019-06-11 14:03:29.885+0000 [id=32033]	INFO	c.c.j.p.amazonecs.ECSLauncher#runECSTask: [jenkins-build-cluster-pbxr1]: Agent started with task arn : arn:aws:ecs:us-east-1:435433059373:task/jenkins-build-cluster/ba7c88b826114baa8b7e864a0fe3faa3
2019-06-11 14:03:29.885+0000 [id=32033]	INFO	c.c.j.p.amazonecs.ECSLauncher#launch: [jenkins-build-cluster-pbxr1]: TaskArn: arn:aws:ecs:us-east-1:435433059373:task/jenkins-build-cluster/ba7c88b826114baa8b7e864a0fe3faa3
2019-06-11 14:03:29.885+0000 [id=32033]	INFO	c.c.j.p.amazonecs.ECSLauncher#launch: [jenkins-build-cluster-pbxr1]: TaskDefinitionArn: arn:aws:ecs:us-east-1:435433059373:task-definition/jenkins-build-cluster-jenkins-ecs-worker:4
2019-06-11 14:03:29.885+0000 [id=32033]	INFO	c.c.j.p.amazonecs.ECSLauncher#launch: [jenkins-build-cluster-pbxr1]: ClusterArn: arn:aws:ecs:us-east-1:435433059373:cluster/jenkins-build-cluster
2019-06-11 14:03:29.885+0000 [id=32033]	INFO	c.c.j.p.amazonecs.ECSLauncher#launch: [jenkins-build-cluster-pbxr1]: ContainerInstanceArn: null
2019-06-11 14:03:30.008+0000 [id=32033]	INFO	c.c.j.p.amazonecs.ECSLauncher#launch: [jenkins-build-cluster-pbxr1]: Waiting for agent to start
2019-06-11 14:03:31.121+0000 [id=32033]	INFO	c.c.j.p.amazonecs.ECSLauncher#launch: [jenkins-build-cluster-pbxr1]: Waiting for agent to start
...
2019-06-11 14:05:01.481+0000 [id=32033]	INFO	c.c.j.p.amazonecs.ECSLauncher#launch: [jenkins-build-cluster-pbxr1]: Waiting for agent to start
2019-06-11 14:05:02.598+0000 [id=32033]	INFO	c.c.j.p.amazonecs.ECSLauncher#launch: [jenkins-build-cluster-pbxr1]: Waiting for agent to start
2019-06-11 14:05:03.711+0000 [id=32033]	INFO	c.c.j.p.amazonecs.ECSLauncher#launch: [jenkins-build-cluster-pbxr1]: Waiting for agent to start
2019-06-11 14:05:04.816+0000 [id=32033]	INFO	c.c.j.p.amazonecs.ECSLauncher#launch: [jenkins-build-cluster-pbxr1]: Waiting for agent to start
2019-06-11 14:05:06.087+0000 [id=32033]	INFO	c.c.j.p.amazonecs.ECSLauncher#launch: [jenkins-build-cluster-pbxr1]: Task started, waiting for agent to become online
2019-06-11 14:05:06.087+0000 [id=32033]	INFO	c.c.j.p.amazonecs.ECSLauncher#launch: [jenkins-build-cluster-pbxr1]: Waiting for agent to connect
2019-06-11 14:05:07.087+0000 [id=32033]	INFO	c.c.j.p.amazonecs.ECSLauncher#launch: [jenkins-build-cluster-pbxr1]: Waiting for agent to connect
2019-06-11 14:06:07.107+0000 [id=32033]	INFO	c.c.j.p.amazonecs.ECSLauncher#launch: [jenkins-build-cluster-pbxr1]: Waiting for agent to connect

... (~50 lines deleted)

2019-06-11 14:06:08.108+0000 [id=32033]	INFO	c.c.j.p.amazonecs.ECSLauncher#launch: [jenkins-build-cluster-pbxr1]: Waiting for agent to connect
2019-06-11 14:06:08.165+0000 [id=32324]	WARNING	h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #39 failed
java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at java.io.DataInputStream.readUTF(DataInputStream.java:609)
	at java.io.DataInputStream.readUTF(DataInputStream.java:564)
	at hudson.TcpSlaveAgentListener$ConnectionHandler.run(TcpSlaveAgentListener.java:264)
2019-06-11 14:06:09.108+0000 [id=32033]	INFO	c.c.j.p.amazonecs.ECSLauncher#launch: [jenkins-build-cluster-pbxr1]: Waiting for agent to connect
2019-06-11 14:06:10.108+0000 [id=32033]	INFO	c.c.j.p.amazonecs.ECSLauncher#launch: [jenkins-build-cluster-pbxr1]: Waiting for agent to connect

... repeats until timeout
```

Details from the running Fargate task look like this:
```
Command | ["-url","https://10.0.3.51:50000/","4c2e4a0152369e721e6dba9854c039506c558a380c012e370fe433f83d524bf7","jenkins-build-cluster-m3wrm"]
-- | --
Privileged: false
Network bindings - not configured
```
Network mode is `awsvpc` and the subnet matches the Jenkins server.

I don't see any errors or anything else that's obviously wrong, but maybe experts here will. Thanks for any help on this.

**Comment by bwolin** [comment]
OK, more information from the container's log:

```SEVERE: Failed to connect to https://10.0.3.51:50000/tcpSlaveAgentListener/: Read timed out
java.io.IOException: Failed to connect to https://10.0.3.51:50000/tcpSlaveAgentListener/: Read timed out
```

I've tried port 8080 also which gets me to other JNLP-Connect problems:

```
Jun 11, 2019 4:12:57 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Protocol JNLP4-connect encountered an unexpected exception
java.util.concurrent.ExecutionException: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Unknown client name: jenkins-build-cluster-f9vjb
	at org.jenkinsci.remoting.util.SettableFuture.get(SettableFuture.java:223)
	at hudson.remoting.Engine.innerRun(Engine.java:614)
	at hudson.remoting.Engine.run(Engine.java:474)
Caused by: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Unknown client name: jenkins-build-cluster-f9vjb
	at org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer.newAbortCause(ConnectionHeadersFilterLayer.java:378)
	at org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer.onRecvClosed(ConnectionHeadersFilterLayer.java:433)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:816)
	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:172)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:816)
	at org.jenkinsci.remoting.protocol.NetworkLayer.onRecvClosed(NetworkLayer.java:154)
	at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer.access$1500(BIONetworkLayer.java:48)
	at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer$Reader.run(BIONetworkLayer.java:247)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.nio.channels.ClosedChannelException
			... 7 more

Jun 11, 2019 4:12:57 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to jenkins.synchr.net:50000
Jun 11, 2019 4:12:57 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Server reports protocol JNLP4-plaintext not supported, skipping
Jun 11, 2019 4:12:57 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Protocol JNLP3-connect is not enabled, skipping
Jun 11, 2019 4:12:57 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Trying protocol: JNLP2-connect
Jun 11, 2019 4:12:57 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Protocol JNLP2-connect encountered an unexpected exception
java.util.concurrent.ExecutionException: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Server didn't accept the handshake: 
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at hudson.remoting.Engine.innerRun(Engine.java:614)
	at hudson.remoting.Engine.run(Engine.java:474)
Caused by: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Server didn't accept the handshake: 
	at org.jenkinsci.remoting.engine.JnlpProtocol2Handler.sendHandshake(JnlpProtocol2Handler.java:138)
	at org.jenkinsci.remoting.engine.LegacyJnlpProtocolHandler$2.call(LegacyJnlpProtocolHandler.java:162)
	at org.jenkinsci.remoting.engine.LegacyJnlpProtocolHandler$2.call(LegacyJnlpProtocolHandler.java:158)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at java.lang.Thread.run(Thread.java:748)

Jun 11, 2019 4:12:57 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to jenkins.synchr.net:50000
Jun 11, 2019 4:12:57 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Trying protocol: JNLP-connect
Jun 11, 2019 4:12:57 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Protocol JNLP-connect encountered an unexpected exception
java.util.concurrent.ExecutionException: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Server didn't accept the handshake: 
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at hudson.remoting.Engine.innerRun(Engine.java:614)
	at hudson.remoting.Engine.run(Engine.java:474)
Caused by: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Server didn't accept the handshake: 
	at org.jenkinsci.remoting.engine.JnlpProtocol1Handler.sendHandshake(JnlpProtocol1Handler.java:123)
	at org.jenkinsci.remoting.engine.LegacyJnlpProtocolHandler$2.call(LegacyJnlpProtocolHandler.java:162)
	at org.jenkinsci.remoting.engine.LegacyJnlpProtocolHandler$2.call(LegacyJnlpProtocolHandler.java:158)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at java.lang.Thread.run(Thread.java:748)

Jun 11, 2019 4:12:57 PM hudson.remoting.jnlp.Main$CuiListener error
SEVERE: The server rejected the connection: None of the protocols were accepted
java.lang.Exception: The server rejected the connection: None of the protocols were accepted
	at hudson.remoting.Engine.onConnectionRejected(Engine.java:682)
	at hudson.remoting.Engine.innerRun(Engine.java:639)
	at hudson.remoting.Engine.run(Engine.java:474)
```

**Comment by webratz** [comment]
Did you configure the security groups to allow the incoming traffic on those ports?
Just guessing as I don't know anything about your infra

**Comment by bwolin** [comment]
I don't think it's the security group blocking it because I see the connection attempt on the server:

```2019-06-12 13:58:29.077+0000 [id=85015]	INFO	h.TcpSlaveAgentListener$ConnectionHandler#run: Accepted JNLP4-connect connection #87 from /10.5.0.12:50672
2019-06-12 13:58:29.387+0000 [id=84962]	INFO	o.j.r.p.i.ConnectionHeadersFilterLayer#onRecv: [JNLP4-connect connection from ip-10-5-0-12.ec2.internal/10.5.0.12:50672] Refusing headers from remote: Unknown client name: jenkins-build-cluster-f9vjb
2019-06-12 13:58:30.165+0000 [id=85016]	WARNING	h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #88 failed
java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at hudson.TcpSlaveAgentListener$ConnectionHandler.run(TcpSlaveAgentListener.java:254)```

**Comment by bwolin** [comment]
I believe the issue is that when Jenkins launches the agent, it registers the alias (e.g. jenkins-build-cluster-92xch) internally and validates that. 

Trying to save time, my test was to manually launch the docker with an old alias that was getting rejected. When I got the final connection URL right (port 8080 instead of 50000,  http instead of https) and launched it again from Jenkins, it finally worked.

**Comment by sathish97625** [comment]
Also, flag public ip in Jenkins cloud configuration, it will resolve the issue, its resolved for us.
