### ISSUE TITLE
Declarative agent cpu/memory override causes "Container.image should not be null or empty"

### ISSUE THREAD

**Issue by mdouglass** [jenkinsci/amazon-ecs-plugin#114]
We have an existing template called ecs-nodejs that defaults memory/cpu to 2048/2048.  That has been working fine using:
```groovy
pipeline {
  agent { label "ecs-nodejs" }
  // ...
}
```

We're looking to override it for a particular build using the following pipeline:
```groovy
pipeline {
  agent { 
    ecs {
      inheritFrom "ecs-nodejs"
      cpu 8192
      memory 4096
    }
  }
  // ...
}
```
  
When that is run, the build never starts and we get the following message in logs:
```
Jul 02, 2019 9:49:14 PM INFO com.cloudbees.jenkins.plugins.amazonecs.pipeline.ECSDeclarativeAgent getAsArgs
In getAsArgs. label: master-25-61z9s
Jul 02, 2019 9:49:14 PM INFO com.cloudbees.jenkins.plugins.amazonecs.pipeline.ECSDeclarativeAgent getAsArgs
In getAsArgs. argMap: {assignPublicIp=false, cpu=8192, inheritFrom=ecs-nodejs, label=master-25-61z9s, memory=4096, name=master-25-61z9s, overrides=[cpu, inheritFrom, memory, label], privileged=false}
Jul 02, 2019 9:49:14 PM INFO com.cloudbees.jenkins.plugins.amazonecs.pipeline.ECSTaskTemplateStepExecution start
Registering task template with name master-25-61z9s-dhc47
Jul 02, 2019 9:49:20 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
Asked to provision 1 agent(s) for: master-25-61z9s
Jul 02, 2019 9:49:20 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
In provisioning : []
Jul 02, 2019 9:49:20 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
Excess workload after pending ECS agents: 1
Jul 02, 2019 9:49:20 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
Will provision ECS Agent master-25-61z9s, for label: master-25-61z9s
Jul 02, 2019 9:49:20 PM INFO hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
Started provisioning ECS Agent master-25-61z9s from ecs-cloud with 1 executors. Remaining excess workload: 0
Jul 02, 2019 9:49:30 PM INFO hudson.slaves.NodeProvisioner$2 run
ECS Agent master-25-61z9s provisioning successfully completed. We have now 4 computer(s)
Jul 02, 2019 9:49:30 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSService findTaskDefinition
No existing task definition found for family or ARN: ecs-cloud-master-25-61z9s-dhc47
Jul 02, 2019 9:49:30 PM WARNING com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[ecs-cloud-s4zpx]: Error in provisioning; agent=com.cloudbees.jenkins.plugins.amazonecs.ECSSlave[ecs-cloud-s4zpx]
com.amazonaws.services.ecs.model.ClientException: Container.image should not be null or empty. (Service: AmazonECS; Status Code: 400; Error Code: ClientException; Request ID: c7ce24a5-090b-470d-b0ae-006ff4876bf6)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.ecs.AmazonECSClient.doInvoke(AmazonECSClient.java:3839)
	at com.amazonaws.services.ecs.AmazonECSClient.invoke(AmazonECSClient.java:3806)
	at com.amazonaws.services.ecs.AmazonECSClient.invoke(AmazonECSClient.java:3795)
	at com.amazonaws.services.ecs.AmazonECSClient.executeRegisterTaskDefinition(AmazonECSClient.java:2666)
	at com.amazonaws.services.ecs.AmazonECSClient.registerTaskDefinition(AmazonECSClient.java:2636)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSService.registerTemplate(ECSService.java:286)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.getTaskDefinition(ECSLauncher.java:201)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.launch(ECSLauncher.java:107)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:294)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)```

**Comment by mdouglass** [comment]
Interestingly the Jenkins master seemed to be in a weird state where it wasn't populating the container image field even though it was set in configuration. Restarting the master caused this error to go away. We are now, however, running into https://github.com/jenkinsci/amazon-ecs-plugin/issues/94
