### ISSUE TITLE
Slave not able to connect to master

### ISSUE THREAD

**Issue by graylancome** [jenkinsci/amazon-ecs-plugin#134]
I went through setup as you specified in the readme in the project but when I kick off a build I am getting connection refused on port 50000. The error message below:

Nov 22, 2019 7:53:23 PM hudson.remoting.jnlp.Main$CuiListener error
SEVERE: Failed to connect to jenkins-elb-293478233.us-east-1.elb.amazonaws.com:50000
java.io.IOException: Failed to connect to jenkins-elb-293478233.us-east-1.elb.amazonaws.com:50000
	at org.jenkinsci.remoting.engine.JnlpAgentEndpoint.open(JnlpAgentEndpoint.java:242)
	at hudson.remoting.Engine.connectTcp(Engine.java:678)
	at hudson.remoting.Engine.innerRun(Engine.java:556)
	at hudson.remoting.Engine.run(Engine.java:488)
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at java.nio.channels.SocketChannel.open(SocketChannel.java:189)
	at org.jenkinsci.remoting.engine.JnlpAgentEndpoint.open(JnlpAgentEndpoint.java:203)
	... 3 more

I have both load balancer and ec2 sg allowing port 50000. Is there something I am doing wrong here? I even exposed 50000 in the Dockerfile for master.

**Comment by bradq** [comment]
Hey @graylancome,

Not a maintainer of this project, but in this case you can take the IOException at face value: your agent is unable to communicate with the listener on the master server. Have you ensured your containers can properly achieve a TCP connection as listed here? 

The issue lies outside the code in this plugin, but I'd suggest ensuring that you can telnet from your ECS EC2 worker instances to the Jenkins server. 2 of the more common issues would be a failing listener on your ELB, or the lack of a firewall rule for the traffic egress from your ECS EC2 instance.
