### ISSUE TITLE
Slave is not getting  registered

### ISSUE THREAD

**Issue by sahotay** [jenkinsci/amazon-ecs-plugin#136]
Seeing the following error while registering the slave in Jenkins. I have tried using "Tunnel connection through" but error changed to ``` Server didn't accept the handshake: HTTP/1.1 400 Illegal character CNTL=0x0```
Could you please help me to debug (FYI slaves are working when I am using EC2 agent plugin to register slaves as EC2 instance).

```
Warning: JnlpProtocol3 is disabled by default, use JNLP_PROTOCOL_OPTS to alter the behavior
Nov 30, 2019 4:22:40 AM hudson.remoting.jnlp.Main createEngine
INFO: Setting up agent: slave-6tplx
Nov 30, 2019 4:22:40 AM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Nov 30, 2019 4:22:41 AM hudson.remoting.Engine startEngine
INFO: Using Remoting version: 3.35
Nov 30, 2019 4:22:41 AM hudson.remoting.Engine startEngine
WARNING: No Working Directory. Using the legacy JAR Cache location: /home/jenkins/.jenkins/cache/jars
Nov 30, 2019 4:22:41 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [http://jenkins-sbox.us-east-1.elb.amazonaws.com/]
Nov 30, 2019 4:22:41 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
INFO: Remoting server accepts the following protocols: [JNLP4-connect, Ping]
Nov 30, 2019 4:22:41 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Agent discovery successful
  Agent address: jenkins-sbox.us-east-1.elb.amazonaws.com
  Agent port:    50000
  Identity:      7d:6d:e3:05:c9:57:27:35:50:5d:9b:e5:91:2c:08:db
Nov 30, 2019 4:22:41 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Handshaking
Nov 30, 2019 4:22:41 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to jenkins-sbox.us-east-1.elb.amazonaws.com:50000
Nov 30, 2019 4:22:41 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Trying protocol: JNLP4-connect
Nov 30, 2019 4:22:41 AM org.jenkinsci.remoting.protocol.impl.AckFilterLayer abort
WARNING: [JNLP4-connect connection to jenkins-sbox.us-east-1.elb.amazonaws.com/10.5.4.23:50000] Incorrect acknowledgement sequence, expected 0x000341434b got 0x485454502f
Nov 30, 2019 4:22:41 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Protocol JNLP4-connect encountered an unexpected exception
java.util.concurrent.ExecutionException: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Connection closed before acknowledgement sent
	at org.jenkinsci.remoting.util.SettableFuture.get(SettableFuture.java:223)
	at hudson.remoting.Engine.innerRun(Engine.java:577)
	at hudson.remoting.Engine.run(Engine.java:488)
Caused by: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Connection closed before acknowledgement sent
	at org.jenkinsci.remoting.protocol.impl.AckFilterLayer.onRecvClosed(AckFilterLayer.java:280)
	at org.jenkinsci.remoting.protocol.FilterLayer.abort(FilterLayer.java:164)
	at org.jenkinsci.remoting.protocol.impl.AckFilterLayer.abort(AckFilterLayer.java:130)
	at org.jenkinsci.remoting.protocol.impl.AckFilterLayer.onRecv(AckFilterLayer.java:258)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecv(ProtocolStack.java:668)
	at org.jenkinsci.remoting.protocol.impl.AgentProtocolClientFilterLayer.onRecv(AgentProtocolClientFilterLayer.java:81)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecv(ProtocolStack.java:668)
	at org.jenkinsci.remoting.protocol.NetworkLayer.onRead(NetworkLayer.java:136)
	at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer.access$2200(BIONetworkLayer.java:48)
	at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer$Reader.run(BIONetworkLayer.java:283)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:97)
	at java.lang.Thread.run(Thread.java:748)
Nov 30, 2019 4:22:41 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to jenkins-sbox.us-east-1.elb.amazonaws.com:50000
Nov 30, 2019 4:22:41 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Server reports protocol JNLP4-plaintext not supported, skipping
Nov 30, 2019 4:22:41 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Protocol JNLP3-connect is not enabled, skipping
Nov 30, 2019 4:22:41 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Server reports protocol JNLP2-connect not supported, skipping
Nov 30, 2019 4:22:41 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Server reports protocol JNLP-connect not supported, skipping
Nov 30, 2019 4:22:41 AM hudson.remoting.jnlp.Main$CuiListener error
SEVERE: The server rejected the connection: None of the protocols were accepted
java.lang.Exception: The server rejected the connection: None of the protocols were accepted
	at hudson.remoting.Engine.onConnectionRejected(Engine.java:662)
	at hudson.remoting.Engine.innerRun(Engine.java:602)
	at hudson.remoting.Engine.run(Engine.java:488)
```

**Comment by webratz** [comment]
Could be that you are trying to connect to the HTTP port, but not the JNLP agent one?

**Comment by WinJayX** [comment]
Protocol JNLP4-connect encountered an unexpected exception
java.util.concurrent.ExecutionException: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Connection closed before acknowledgement sent

**Comment by devopsmatt** [comment]
Bump
