### ISSUE TITLE
Issue mounting docker.sock in ECS

### ISSUE THREAD

**Issue by adoylesimplisafe** [jenkinsci/amazon-ecs-plugin#137]
Hello,

I'm trying to figure out how to mount `docker.sock` to the ECS Jenkins agent so that I can spawn other containers for specific build steps.  I am having trouble getting it to work properly.

My latest attempt:
```
pipeline {
    agent {
        ecs {
            cloud 'qa-east-agent-cloud'
            label 'qa-east-agent'
            memory 1024
            image 'ninech/jnlp-slave-with-docker'
            mountPoints([
                [
                    name: 'docker_socket', 
                    sourcePath:'unix:///var/run/docker.sock', 
                    containerPath:'unix:///var/run/docker.sock',
                    readOnly: false
                ]
            ])
        }
    }
...
```
I'm not sure if this is the correct syntax as it's not documented anywhere, this is my best attempt I could derive from the code (as I am not an experienced Java developer).

I'm noticing in the logs that these override variables may not actually be applied:
```
2019-12-06 21:30:02.146+0000 [id=1528]	INFO	c.c.j.p.a.p.ECSDeclarativeAgent#getAsArgs: In getAsArgs. argMap: {assignPublicIp=false, cloud=qa-east-agent-cloud, image=ninech/jnlp-slave-with-docker, label=qa-east-agent, memory=1024, name=qa-east-agent, overrides=[cloud, image, label, memory, mountPoints], privileged=false}
```
Then below:
```
2019-12-06 21:30:18.600+0000 [id=1450]	INFO	c.c.j.p.amazonecs.ECSService#registerTemplate: Created Task Definition: {TaskDefinitionArn: arn:aws:ecs:us-east-1:618804428340:task-definition/qa-east-agent-cloud-qa-east-agent-q9tn0:1,ContainerDefinitions: [{Name: qa-east-agent-cloud-qa-east-agent-q9tn0,Image: ninech/jnlp-slave-with-docker,Cpu: 0,Memory: 1024,Links: [],PortMappings: [],Essential: true,EntryPoint: [],Command: [],Environment: [],MountPoints: [],VolumesFrom: [],Secrets: [],DependsOn: [],Privileged: false,DnsServers: [],DnsSearchDomains: [],ExtraHosts: [],DockerSecurityOptions: [],Ulimits: [],SystemControls: [],ResourceRequirements: [],}],Family: qa-east-agent-cloud-qa-east-agent-q9tn0,Revision: 1,Volumes: [],Status: ACTIVE,RequiresAttributes: [],PlacementConstraints: [],Compatibilities: [EC2],RequiresCompatibilities: [],InferenceAccelerators: [],}
```
Specifically, `MountPoints: []`. Confirmed that this is also an empty list in the resulting task definition.

I noticed in this pull request (https://github.com/jenkinsci/amazon-ecs-plugin/pull/13) this use case is specifically referenced in the comments, but I am having trouble finding examples.

Can anyone point me in the right direction?

Thanks.

**Comment by mcintyre321** [comment]
hi, did you get thisworking? any pointers?

**Comment by webratz** [comment]
I don't have it in CASC, but our config looks like this in the UI and it works fine
![Screen Shot 2020-01-31 at 1 04 56 PM](https://user-images.githubusercontent.com/2162832/73538076-52ff4e00-442a-11ea-92a5-2d4bfa8a562f.png)

**Comment by Yamaha32088** [comment]
> I don't have it in CASC, but our config looks like this in the UI and it works fine
> ![Screen Shot 2020-01-31 at 1 04 56 PM](https://user-images.githubusercontent.com/2162832/73538076-52ff4e00-442a-11ea-92a5-2d4bfa8a562f.png)

This was the ticket for use to be able to run a Docker container inside of the ECS task. Thanks for posting this!

**Comment by FilipSwiatczak** [comment]
> I don't have it in CASC, but our config looks like this in the UI and it works fine
> ![Screen Shot 2020-01-31 at 1 04 56 PM](https://user-images.githubusercontent.com/2162832/73538076-52ff4e00-442a-11ea-92a5-2d4bfa8a562f.png)

hello @webratz I'm looking to get basic docker in docker running with this fargate plugin. Simply to call docker run inside a jenkinsfile stage. Using same image as in this thread "ninech/jnlp-slave-with-docker". Following quoted advice, I'm getting: 
`Asked to provision 1 agent(s) for: ecs-dind
Jul 14, 2020 4:53:50 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
Will provision Fargate-ecs-dind-d3br6, for label: ecs-dind
Jul 14, 2020 4:54:00 PM INFO hudson.slaves.NodeProvisioner lambda$update$6
Fargate-ecs-dind-d3br6 provisioning successfully completed. We have now 3 computer(s)
Jul 14, 2020 4:54:00 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSService findTaskDefinition
No existing task definition found for family or ARN: Fargate-FARGATE-dind
Jul 14, 2020 4:54:00 PM WARNING com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[Fargate-ecs-dind-d3br6]: Error in provisioning; agent=com.cloudbees.jenkins.plugins.amazonecs.ECSSlave[Fargate-ecs-dind-d3br6]
com.amazonaws.services.ecs.model.ClientException: host.sourcePath should not be set for volumes in Fargate. (Service: AmazonECS; Status Code: 400; Error Code: ClientException; Request ID: 4c4cafe8-a33e-437e-9577-e5087b79f193; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.ecs.AmazonECSClient.doInvoke(AmazonECSClient.java:4249)
	at com.amazonaws.services.ecs.AmazonECSClient.invoke(AmazonECSClient.java:4216)
	at com.amazonaws.services.ecs.AmazonECSClient.invoke(AmazonECSClient.java:4205)
	at com.amazonaws.services.ecs.AmazonECSClient.executeRegisterTaskDefinition(AmazonECSClient.java:2924)
	at com.amazonaws.services.ecs.AmazonECSClient.registerTaskDefinition(AmazonECSClient.java:2894)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSService.registerTemplate(ECSService.java:316)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.launchECSTask(ECSLauncher.java:148)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.launch(ECSLauncher.java:110)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:296)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

Am I missing something here? Is fargate even able to run docker in docker, as per "host.sourcePath should not be set for volumes in Fargate". Thank you for your help.

**Comment by webratz** [comment]
Docker in Docker AFAIK does not work with Fargate

**Comment by FilipSwiatczak** [comment]
thank you for clarifying @webratz, makes sense! Changing the Launch type from Fargate to EC2 and using above Container Mount Points could therefore work as far as the plugin is concerned? Thanks again

**Comment by mcintyre321** [comment]
Yes, that worked for me. One thing to bear in mind when mounting the socket
like that, is that mounted volumes still map to host volumes:
https://stackoverflow.com/questions/50971417/docker-inside-docker-volume-is-mounted-but-empty

**Comment by GingaNinja** [comment]
I've set the mounts as suggested by @webratz, but I'm thinking I have permissions issues on the ec2 host for the docker.sock file - docker can't see the sock file inside the container. Is there something you've done to get the permissions correct? It's using the Jenkins user in the container, which I suspect is the problem.
