### ISSUE TITLE
After jenkins is deployed ECS plugin requires manual apply

### ISSUE THREAD

**Issue by connaryscott** [jenkinsci/amazon-ecs-plugin#168]
Not sure why this happens.

we use helm to deploy the jenkins master.
ECS agents are offline and jobs do not start.
I go in and apply the configuration MANUALLY (https://my-jenkins/jenkins/configure)
and ecs agents magically start and jobs run.

Our kubernetes plugin does not do this (and of course more motivation to get off of ecs).

any idea why i would need to do this?

**Comment by wwalasekperform** [comment]
We experienced a similar issue. We have two separate Jenkins instances and after each deploy, restart or simple 'reload configuration from disk' our jobs were not starting until we changed template names manually. This has to be done every time.

Jenkins instance one:
Jenkins version 2.235
Plugin version 1.34

Jenkins instance two
Jenkins version 2.202
Plugin version 1.36

I will update this issue with logs from Jenkins after next occurrence.

**Comment by wwalasekperform** [comment]
Promised logs 
`2020-07-17 08:42:22.106+0000 [id=1087]	WARNING	c.c.j.p.amazonecs.ECSLauncher#runECSTask: [ecs-cloud-london-ecs-london-5v3l5]: Failure to run task with definition arn:aws:ecs:eu-west-2:193627599092:task-definition/ecs-cloud-london-qa-slave-london-template:5 on ECS cluster arn:aws:ecs:eu-west-2:193627599092:cluster/QA-Jenkins-Slaves-ECS
2020-07-17 08:42:22.112+0000 [id=1087]	WARNING	c.c.j.p.amazonecs.ECSLauncher#runECSTask: [ecs-cloud-london-ecs-london-5v3l5]: Failure reason=RESOURCE:CPU, arn=arn:aws:ecs:eu-west-2:193627599092:container-instance/0e3f22d3-8220-48c7-86f3-89a43aff04ad
2020-07-17 08:42:22.113+0000 [id=1087]	WARNING	c.c.j.p.amazonecs.ECSLauncher#runECSTask: [ecs-cloud-london-ecs-london-5v3l5]: Failure reason=RESOURCE:CPU, arn=arn:aws:ecs:eu-west-2:193627599092:container-instance/99358ea5-b9f7-4966-8fa8-538b09e027c8
2020-07-17 08:42:22.113+0000 [id=1087]	WARNING	c.c.j.p.amazonecs.ECSLauncher#runECSTask: [ecs-cloud-london-ecs-london-5v3l5]: Failure reason=RESOURCE:CPU, arn=arn:aws:ecs:eu-west-2:193627599092:container-instance/e2fdcfbd-7db0-4091-b422-1df439664096
2020-07-17 08:42:22.113+0000 [id=1087]	WARNING	c.c.j.p.amazonecs.ECSLauncher#launch: [ecs-cloud-london-ecs-london-5v3l5]: Error in provisioning; agent=com.cloudbees.jenkins.plugins.amazonecs.ECSSlave[ecs-cloud-london-ecs-london-5v3l5]
hudson.AbortException: Failed to run agent container ecs-cloud-london-ecs-london-5v3l5
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.runECSTask(ECSLauncher.java:220)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.launchECSTask(ECSLauncher.java:149)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.launch(ECSLauncher.java:110)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:293)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-07-17 08:42:22.116+0000 [id=36]	INFO	hudson.slaves.NodeProvisioner#lambda$update$6: ecs-cloud-london-ecs-london-4n0q2 provisioning successfully completed. We have now 15 computer(s)
2020-07-17 08:42:22.202+0000 [id=1139]	INFO	h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #389 failed: java.io.EOFException
2020-07-17 08:42:22.202+0000 [id=36]	INFO	hudson.slaves.NodeProvisioner#lambda$update$6: ecs-cloud-london-ecs-london-h214c provisioning successfully completed. We have now 16 computer(s)
2020-07-17 08:42:22.224+0000 [id=523]	INFO	c.c.j.p.amazonecs.ECSService#registerTemplate: Match on container definition: true
2020-07-17 08:42:22.233+0000 [id=523]	INFO	c.c.j.p.amazonecs.ECSService#registerTemplate: Match on volumes: true
2020-07-17 08:42:22.233+0000 [id=523]	INFO	c.c.j.p.amazonecs.ECSService#registerTemplate: Match on task role: true
2020-07-17 08:42:22.233+0000 [id=523]	INFO	c.c.j.p.amazonecs.ECSService#registerTemplate: Match on execution role: true
2020-07-17 08:42:22.233+0000 [id=523]	INFO	c.c.j.p.amazonecs.ECSService#registerTemplate: Match on network mode: true`

**Comment by wwalasekperform** [comment]
We also saw errors with NullPointer exception:
```
2020-07-17 08:34:49.335+0000 [id=656]	WARNING	c.c.j.p.amazonecs.ECSLauncher#launch: [ecs-cloud-london-ecs-london-1cl4k]: Error in provisioning; agent=com.cloudbees.jenkins.plugins.amazonecs.ECSSlave[ecs-cloud-london-ecs-london-1cl4k]
java.lang.NullPointerException
	at com.cloudbees.jenkins.plugins.amazonecs.ECSService.registerTemplate(ECSService.java:193)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.launchECSTask(ECSLauncher.java:148)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.launch(ECSLauncher.java:110)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:293)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-07-17 08:34:49.374+0000 [id=24]	INFO	hudson.slaves.NodeProvisioner#lambda$update$6: ecs-cloud-london-ecs-london-1cl4k provisioning successfully completed. We have now 5 computer(s)
```

**Comment by wwalasekperform** [comment]
This is probably has been unnoticed as duplicate #187 has more traction. It could potentially be closed and moved into one discussion.
