### ISSUE TITLE
Plugin stopped working after updating Jenkins to 2.235 - using a specific task definition

### ISSUE THREAD

**Issue by amiryeshooroon** [jenkinsci/amazon-ecs-plugin#180]
Hello,

I have used this great plugin for few months, and after upgrading today Jenkins to 2.235 ([changelog](https://www.jenkins.io/changelog/)), the plugin stopped working when I am specifying a specific task definition (this is **not** the first time that I am trying to launch an agent using this task definition). If I am not specifying any task definition, then the agent will be launched without any problems.

Log:

```
Asked to provision 1 agent(s) for: image-builder
May 07, 2020 8:07:13 AM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
Will provision ecs-cloud-image-builder-88s7f, for label: image-builder
May 07, 2020 8:07:23 AM WARNING com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[ecs-cloud-image-builder-88s7f]: Error in provisioning; agent=com.cloudbees.jenkins.plugins.amazonecs.ECSSlave[ecs-cloud-image-builder-88s7f]
java.lang.NullPointerException
	at com.cloudbees.jenkins.plugins.amazonecs.ECSService.findTaskDefinition(ECSService.java:306)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.getTaskDefinition(ECSLauncher.java:210)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.launch(ECSLauncher.java:107)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:296)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

May 07, 2020 8:07:23 AM INFO hudson.slaves.NodeProvisioner lambda$update$6
ecs-cloud-image-builder-88s7f provisioning successfully completed. We have now 5 computer(s)
May 07, 2020 8:07:33 AM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
Asked to provision 1 agent(s) for: image-builder
May 07, 2020 8:07:33 AM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
Will provision ecs-cloud-image-builder-4zmpm, for label: image-builder
May 07, 2020 8:07:43 AM WARNING com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[ecs-cloud-image-builder-4zmpm]: Error in provisioning; agent=com.cloudbees.jenkins.plugins.amazonecs.ECSSlave[ecs-cloud-image-builder-4zmpm]
java.lang.NullPointerException
	at com.cloudbees.jenkins.plugins.amazonecs.ECSService.findTaskDefinition(ECSService.java:306)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.getTaskDefinition(ECSLauncher.java:210)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.launch(ECSLauncher.java:107)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:296)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Jenkins is trying to launch the agent again and again, but it keeps failing.

**Comment by amiryeshooroon** [comment]
It looks like if you are specifying a task definition in the plugin configurations, you need to remove it, build once, and then add it back. That solved the problem for me.
I hope that it will help more people.

**Comment by CpuID** [comment]
We just hit this issue also :( @amiryeshooroon can you advise on exactly what you removed, and readded? Did you have to do this for every single job?

We use a task definition override for every single job we run, as we have lang/version targeted task definitions (for smaller agent images) in place. Would this imply we have to remove the override from every task template defined, then execute *every* single job once, then re-add?

**Comment by CpuID** [comment]
This feels like it should be reopened, while there's a workaround there is a bug that should be resolved (an NPE), to avoid others hitting the same issue.

I just confirmed, we use task definition overrides instead of template names, as we manage all of our ECS task definitions externally and then specify the family:revision in the UI (we actually do this via rewriting config.xml in bulk and reloading, but same concept).

**Comment by amiryeshooroon** [comment]
> We just hit this issue also :( @amiryeshooroon can you advise on exactly what you removed, and readded? Did you have to do this for every single job?
> 
> We use a task definition override for every single job we run, as we have lang/version targeted task definitions (for smaller agent images) in place. Would this imply we have to remove the override from every task template defined, then execute _every_ single job once, then re-add?

For each cloud agent (label) you have, try to:
- remove the task definition override
- build a job that uses this label
- put back the task definition (same one)
- build again

That fixed the problem for me.

**Comment by CpuID** [comment]
@amiryeshooroon thx, yea we ended up deleting all of our cloud templates and just regenerated them (programmatically). We didn't have to kick off a job in between luckily.

For maintainers: I still think this deserves to be reopened.
