### ISSUE TITLE
Jobs with custom task definition fail to launch with findTaskDefinition error

### ISSUE THREAD

**Issue by jeffj254** [jenkinsci/amazon-ecs-plugin#203]
Jenkins: 2.204.6
ECS Plugin: 1.34

We've been running into an intermittent issue with jobs suddenly failing to launch with a NullPointerException for findTaskDefinition.  This issue did not occur until we started using custom task definitions.  We will run for days without any issues, but suddenly all jobs will fail to launch with the NPE error.  The resolution is to re-apply the cloud config by removing and reseting the task override name.  As soon as that is done, all jobs start launching successfully again.  It seems like this may be related to #187 since the behavior and resolution are similar.  The full error is:

```
2020-06-26 14:59:50.799+0000 [id=78834]	WARNING	c.c.j.p.amazonecs.ECSLauncher#launch: [*******-ms8kk]: Error in provisioning; agent=com.cloudbees.jenkins.plugins.amazonecs.ECSSlave[********-ms8kk]
java.lang.NullPointerException
	at com.cloudbees.jenkins.plugins.amazonecs.ECSService.findTaskDefinition(ECSService.java:306)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.getTaskDefinition(ECSLauncher.java:210)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.launch(ECSLauncher.java:107)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:292)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

It seems like something is causing the cloud config to be either wiped or corrupted such that the ECS plugin cannot find the correct task definition to use anymore.  The logs don't show anything more than the error listed above.  Is there any additional debug logging we can turn on?

**Comment by wuillaum** [comment]
I believe this is a dup of https://github.com/jenkinsci/amazon-ecs-plugin/issues/187
