### ISSUE TITLE
ECS basic setup

### ISSUE THREAD

**Issue by rrodriguez-logn** [jenkinsci/amazon-ecs-plugin#217]
Hi,
For some reason I'm getting the following error with the most basic configuration:
**Problem:**
```
[jenkins-slave-jenkins-slave-8zk1p]: Error in provisioning; agent=com.cloudbees.jenkins.plugins.amazonecs.ECSSlave[jenkins-slave-jenkins-slave-8zk1p]
com.amazonaws.services.ecs.model.InvalidParameterException: No Container Instances were found in your cluster. (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 347ecfa0-426b-4c45-aaf6-a63748646ce5; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.ecs.AmazonECSClient.doInvoke(AmazonECSClient.java:4332)
	at com.amazonaws.services.ecs.AmazonECSClient.invoke(AmazonECSClient.java:4299)
	at com.amazonaws.services.ecs.AmazonECSClient.invoke(AmazonECSClient.java:4288)
	at com.amazonaws.services.ecs.AmazonECSClient.executeRunTask(AmazonECSClient.java:3118)
	at com.amazonaws.services.ecs.AmazonECSClient.runTask(AmazonECSClient.java:3089)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSService.runEcsTask(ECSService.java:434)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.runECSTask(ECSLauncher.java:213)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.launchECSTask(ECSLauncher.java:149)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.launch(ECSLauncher.java:110)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:294)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Expected:**
I followed this example step by step, but at the end it looks that for some reason the configuration at my end is not working properly.
[https://www.youtube.com/watch?v=_3umLU9QjZI](https://www.youtube.com/watch?v=_3umLU9QjZI)

**Comment by bradq** [comment]
That error originates from ECS rather than this plugin. Your ECS cluster doesn't have any running and registered EC2 instances to host containers. The [ECS documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_container_instance.html) should be helpful for adding an instance to your cluster.
