### ISSUE TITLE
Better error detection

### ISSUE THREAD

**Issue by TheCrockett** [jenkinsci/amazon-ecs-plugin#301]
### What feature do you want to see added?

-- No idea what this means, so I can't troubleshoot. Whatever the issue is, should at minimum be in the log more clearly. 

EC2-Fargate-builder-EC2-Fargate-builder-h7ff5 provisioning successfully completed. We have now 4 computer(s)

Dec 06, 2022 3:02:40 AM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSService findTaskDefinition

No existing task definition found for family or ARN: EC2-Fargate-builder-jenkinsTask-fb9b65e9-7630-402d-a968-36c486f14188

Dec 06, 2022 3:02:40 AM WARNING com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch

[EC2-Fargate-builder-EC2-Fargate-builder-h7ff5]: Error in provisioning; agent=com.cloudbees.jenkins.plugins.amazonecs.ECSSlave[EC2-Fargate-builder-EC2-Fargate-builder-h7ff5]
java.lang.NullPointerException
	at com.cloudbees.jenkins.plugins.amazonecs.ECSService.registerTemplate(ECSService.java:310)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.launchECSTask(ECSLauncher.java:148)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.launch(ECSLauncher.java:110)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:298)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:48)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:82)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by Stericson** [comment]
The task definition you're referencing doesn't exist. You need to create it.
