### ISSUE TITLE
Amazon Elastic Container Service (ECS) / Fargate plugin Version1.48 is not working

### ISSUE THREAD

**Issue by venkatesh588** [jenkinsci/amazon-ecs-plugin#323]
### Jenkins and plugins versions report

Hi Team,

I have installed Amazon Elastic Container Service (ECS) / Fargate plugin Version1.48 in my Jenkins and executing the agents. But the agent is not coming up using the latest version of Amazon Elastic Container Service (ECS) / Fargate plugin. I'm running my master Jenkins with [Jenkins 2.401.1](https://www.jenkins.io/) version. I have separate slave cluster for Master and slave and our Jenkins master and slave hosted on Amazon ECS.  The agents are working with Amazon Elastic Container Service (ECS) / Fargate plugin Version1.37 in the Jenkins LTS version. 

Please find the below logs. 

Will provision ECS_SLAVE_CLOUD_1-Jenkins-JNLP-Debian-ppx79, for label: Jenkins-JNLP-Debian
Jul 27, 2023 1:03:41 PM SEVERE hudson.triggers.SafeTimerTask run
Timer task hudson.slaves.NodeProvisioner$NodeProvisionerInvoker@4c4392f4 failed
java.lang.IllegalArgumentException
	at hudson.slaves.NodeProvisioner$PlannedNode.<init>(NodeProvisioner.java:102)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSCloud.provision(ECSCloud.java:292)
	at io.jenkins.plugins.aws.lambda.cloud.LambdaCloudProvisionerStrategy.apply(LambdaCloudProvisionerStrategy.java:80)
	at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:325)
	at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:823)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:92)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:67)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

Jul 27, 2023 1:03:51 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
Asked to provision 1 agent(s) for: Jenkins-JNLP-Debian
Jul 27, 2023 1:03:51 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
Will provision ECS_SLAVE_CLOUD_1-Jenkins-JNLP-Debian-3cngt, for label: Jenkins-JNLP-Debian
Jul 27, 2023 1:03:51 PM SEVERE hudson.triggers.SafeTimerTask run
Timer task hudson.slaves.NodeProvisioner$NodeProvisionerInvoker@4c4392f4 failed
java.lang.IllegalArgumentException
	at hudson.slaves.NodeProvisioner$PlannedNode.<init>(NodeProvisioner.java:102)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSCloud.provision(ECSCloud.java:292)
	at io.jenkins.plugins.aws.lambda.cloud.LambdaCloudProvisionerStrategy.apply(LambdaCloudProvisionerStrategy.java:80)
	at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:325)
	at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:823)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:92)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:67)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

### What Operating System are you using (both controller, and any agents involved in the problem)?

I'm running Master and slave on Linux. 

### Reproduction steps

Please install master on ECS cluster and slave on different ECS cluster. 
Create the agent image and configure in the cloud section. 
Run the pipeline on the slave nodes. 

### Expected Results

The task should come up in the salve node. 

### Actual Results

The task is not coming up in the slave nodes.

**Comment by svanscho** [comment]
I have the same issue. 1.47 also no longer works.

**Comment by mauricioramirezh** [comment]
I have the same issue. have they found a solution?

**Comment by owengo** [comment]
Same problem here when trying to ugprade from 1.41 => 1.49.

After some investigations ( thanks git blame !) it seems the change came at 1.45 with the "num executors", a solution is provided here:
https://github.com/jenkinsci/amazon-ecs-plugin/issues/291

You have to manually edit your cloud configurations and add: Number of executors per agent = 1 ( default is 0 and causes the error )
