### ISSUE TITLE
taskDefinitionOverride ignored while cleaning up the resources

### ISSUE THREAD

**Issue by Shanjohn** [jenkinsci/amazon-ecs-plugin#98]
Hi guys! I'm trying to run fargate agent, and because of the [issue 95](https://github.com/jenkinsci/amazon-ecs-plugin/issues/95) I've set up template using my custom task definition. However, I encountered another error - plugin seems to not know that task definition was overrided and it still tries to remove non-existant generic task definition.

[Pipeline] Start of Pipeline
[Pipeline] stage
[Pipeline] { (Test)
[Pipeline] ecsTaskTemplate
[Pipeline] {
[Pipeline] node
Still waiting to schedule task
‘ecs-cloud-jenkins-jq429’ is offline
Running on ecs-cloud-jenkins-jq429 in /home/jenkins/workspace/jenkins-test
[Pipeline] {
[Pipeline] sh
+ echo hello
hello
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // ecsTaskTemplate
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

java.lang.NullPointerException
	at com.cloudbees.jenkins.plugins.amazonecs.ECSService.removeTemplate(ECSService.java:298)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSCloud.removeDynamicTemplate(ECSCloud.java:353)
	at com.cloudbees.jenkins.plugins.amazonecs.pipeline.ECSTaskTemplateStepExecution$ECSTaskTemplateCallback.finished(ECSTaskTemplateStepExecution.java:185)
	at org.jenkinsci.plugins.workflow.steps.BodyExecutionCallback$TailCall.onSuccess(BodyExecutionCallback.java:118)
	at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$SuccessAdapter.receive(CpsBodyExecution.java:377)
	at com.cloudbees.groovy.cps.Outcome.resumeFrom(Outcome.java:73)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:166)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:174)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:347)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:93)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:259)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:247)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE

In Jenkins logs:
May 20, 2019 10:04:35 PM com.cloudbees.jenkins.plugins.amazonecs.pipeline.ECSDeclarativeAgent getAsArgs
INFO: In getAsArgs. label: jenkins-test-36-xsskl
May 20, 2019 10:04:35 PM com.cloudbees.jenkins.plugins.amazonecs.pipeline.ECSDeclarativeAgent getAsArgs
INFO: In getAsArgs. argMap: {assignPublicIp=false, cpu=1024, inheritFrom=base-template, label=jenkins-test-36-xsskl, name=jenkins-test-36-xsskl, overrides=[cpu, inheritFrom, label], privileged=false}
May 20, 2019 10:04:35 PM com.cloudbees.jenkins.plugins.amazonecs.pipeline.ECSTaskTemplateStepExecution start
INFO: Registering task template with name jenkins-test-36-xsskl-62wj9
May 20, 2019 10:04:45 PM com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
INFO: Asked to provision 1 agent(s) for: jenkins-test-36-xsskl
May 20, 2019 10:04:45 PM com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
INFO: In provisioning : []
May 20, 2019 10:04:45 PM com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
INFO: Excess workload after pending ECS agents: 1
May 20, 2019 10:04:45 PM com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
INFO: Will provision ECS Agent jenkins-test-36-xsskl, for label: jenkins-test-36-xsskl
May 20, 2019 10:04:45 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning ECS Agent jenkins-test-36-xsskl from ecs-cloud-jenkins with 1 executors. Remaining excess workload: 0
May 20, 2019 10:04:55 PM hudson.slaves.NodeProvisioner$2 run
INFO: ECS Agent jenkins-test-36-xsskl provisioning successfully completed. We have now 2 computer(s)
May 20, 2019 10:04:55 PM com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher runECSTask
INFO: [ecs-cloud-jenkins-t5lv9]: Starting agent with task definition arn:aws:ecs:region:xxxxxxxxxxxx:task-definition/jenkins-agent:7}
May 20, 2019 10:04:56 PM com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher runECSTask
INFO: [ecs-cloud-jenkins-t5lv9]: Agent started with task arn : arn:aws:ecs:region:xxxxxxxxxxxx:task/fb86408c-4d22-4c3b-b47c-286e74b8207b
May 20, 2019 10:04:56 PM com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
INFO: [ecs-cloud-jenkins-t5lv9]: TaskArn: arn:aws:ecs:region:xxxxxxxxxxxx:task/fb86408c-4d22-4c3b-b47c-286e74b8207b
May 20, 2019 10:04:56 PM com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
INFO: [ecs-cloud-jenkins-t5lv9]: TaskDefinitionArn: arn:aws:ecs:region:xxxxxxxxxxxx:task-definition/jenkins-agent:7
May 20, 2019 10:04:56 PM com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
INFO: [ecs-cloud-jenkins-t5lv9]: ClusterArn: arn:aws:ecs:region:xxxxxxxxxxxx:cluster/jenkins-clu
...
May 20, 2019 10:06:24 PM com.cloudbees.jenkins.plugins.amazonecs.ECSSlave _terminate
INFO: [ecs-cloud-jenkins-t5lv9]: Stopping: TaskArn arn:aws:ecs:region:xxxxxxxxxxxx:task/fb86408c-4d22-4c3b-b47c-286e74b8207b, ClusterArn arn:aws:ecs:region:xxxxxxxxxxxx:cluster/jenkins-clu
May 20, 2019 10:06:24 PM com.cloudbees.jenkins.plugins.amazonecs.ECSService stopTask
INFO: Delete ECS agent task: arn:aws:ecs:region:xxxxxxxxxxxx:task/fb86408c-4d22-4c3b-b47c-286e74b8207b
May 20, 2019 10:06:24 PM com.cloudbees.jenkins.plugins.amazonecs.pipeline.ECSTaskTemplateStepExecution$ECSTaskTemplateCallback finished
INFO: Removing task template jenkins-test-36-xsskl-62wj9 from cloud ecs-cloud-jenkins
May 20, 2019 10:06:24 PM com.cloudbees.jenkins.plugins.amazonecs.ECSService findTaskDefinition
INFO: No existing task definition found for family or ARN: ecs-cloud-jenkins-jenkins-test-36-xsskl-62wj9
May 20, 2019 10:06:24 PM jenkins.slaves.DefaultJnlpSlaveReceiver channelClosed
WARNING: Computer.threadPoolForRemoting [#110] for ecs-cloud-jenkins-t5lv9 terminated
java.nio.channels.ClosedChannelException
        at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:209)
        at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:222)
        at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:816)
        at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)
        at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:181)
        at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:283)
        at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:503)
        at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:248)
        at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:200)
        at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:213)
        at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:784)
        at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:173)
        at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:314)
        at hudson.remoting.Channel.close(Channel.java:1452)
        at hudson.remoting.Channel.close(Channel.java:1405)
        at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:832)
        at hudson.slaves.SlaveComputer.kill(SlaveComputer.java:799)
        at hudson.model.AbstractCIBase.killComputer(AbstractCIBase.java:88)
        at hudson.model.AbstractCIBase.updateComputerList(AbstractCIBase.java:227)
        at jenkins.model.Jenkins.updateComputerList(Jenkins.java:1581)
        at jenkins.model.Nodes$6.run(Nodes.java:261)
        at hudson.model.Queue._withLock(Queue.java:1381)
        at hudson.model.Queue.withLock(Queue.java:1258)
        at jenkins.model.Nodes.removeNode(Nodes.java:252)
        at jenkins.model.Jenkins.removeNode(Jenkins.java:2096)
        at hudson.slaves.AbstractCloudSlave.terminate(AbstractCloudSlave.java:70)
        at org.jenkinsci.plugins.durabletask.executors.OnceRetentionStrategy$1$1.run(OnceRetentionStrategy.java:128)
        at hudson.model.Queue._withLock(Queue.java:1381)
        at hudson.model.Queue.withLock(Queue.java:1258)
        at org.jenkinsci.plugins.durabletask.executors.OnceRetentionStrategy$1.run(OnceRetentionStrategy.java:123)
        at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

May 20, 2019 10:06:25 PM org.jenkinsci.plugins.workflow.job.WorkflowRun finish
INFO: my-repo/my-project #36 completed: FAILURE

**Comment by webratz** [comment]
as #95 is now closed (not yet released, but you can try the latest dev build) , does that also fix you issue?

**Comment by Shanjohn** [comment]
It is good news about #95 , but this issue still exists and it makes taskDefinitionOverride kind of useless. The logic is strange - plugin tries to delete some generic task definition which hasn't been created because of using taskDefinitionOverride. All build steps are successful, but build always fails because it is impossible to delete task definition that hasn't been created in a first place.

**Comment by webratz** [comment]
I understand the problem, but i'm currently quite constrained on how much time i can put into this plugin. If you find some time I'm happy to review and test a PR for that if you plan to create one

**Comment by webratz** [comment]
This should be fixed with the linked PR. there is a 1.21-beta now which you could use to verify

**Comment by webratz** [comment]
1.21 was just released
